export let data = [
  {
    // _id: 1,
    name: "Panjabi",
    img: "/images/shirt-1.jpg",
    slug: "panjabi",
    price: 260,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Illian",
    rating: "5",
    numberofrating: 120,
    stock: 220,
    catagroy: "one",
    cupon: "ami",
    discount: 40,
    limit: 100,
    totalSale: 120,
  },

  {
    // _id: 2,
    name: "Shirt",
    img: "/images/shirt-2.jpg",
    slug: "shirt",
    price: 160,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Smart Man",
    rating: "3.5",
    numberofrating: 20,
    stock: 120,
    catagroy: "one",
    cupon: "ami",
    discount: 40,
    limit: 100,
    totalSale: 120,
  },
  {
    // _id: 3,
    name: "Pant",
    img: "/images/shirt-3.jpg",
    slug: "pant",
    price: 80,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Denim",
    rating: "4",
    numberofrating: 240,
    stock: 0,
    catagroy: "one",
    cupon: "ami",
    discount: 40,
    limit: 100,
    totalSale: 120,
  },
  {
    // _id: 4,
    name: "T-Shirt",
    img: "/images/shirt-4.jpg",
    slug: "t-shirt",
    price: 120,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Adidas",
    rating: "3.5",
    numberofrating: 60,
    stock: 20,
    catagroy: "one",
    cupon: "ami",
    discount: 40,
    limit: 100,
    totalSale: 120,
  },
  {
    // _id: 5,
    name: "T-Shirt-2",
    img: "/images/shirt-4.jpg",
    slug: "t-shirt-two",
    price: 120,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Adidas",
    rating: "3.5",
    numberofrating: 60,
    stock: 20,
    catagroy: "one",
    cupon: "ami",
    discount: 40,
    limit: 100,
    totalSale: 120,
  },
  {
    // _id: 6,
    name: "Pant-2",
    img: "/images/shirt-3.jpg",
    slug: "pant-two",
    price: 80,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Denim",
    rating: "4",
    numberofrating: 240,
    stock: 0,
    catagroy: "two",
    totalSale: 20,
  },
  {
    // _id: 7,
    name: "Panjabi-2",
    img: "/images/shirt-1.jpg",
    slug: "panjabi-two",
    price: 260,
    description: "Text messaging, or texting, is the act of composing and sending electronic messages",
    brand: "Illian",
    rating: "5",
    numberofrating: 120,
    stock: 220,
    catagroy: "one",
    totalSale: 30,
  },
];
